### PR TITLE
Macaulay2 patch

### PR DESCRIPTION
**Pull request by mahrud**
You might need to reset to this commit instead, like in #6

### CODE REVIEW

**Comment by DanGrayson** [comment]
I think, for clarity, we should keep the branch "trunk" in agreement with the upstream branch of the same name, and use the branch Macaulay2-patch to contain the trunk plus our patches, as was done before.  I'll take care of that...

**Comment by DanGrayson** [comment]
> I think, for clarity, we should keep the branch "trunk" in agreement with the upstream branch of the same name, and use the branch Macaulay2-patch to contain the trunk plus our patches, as was done before. I'll take care of that...

Hmm, that branch is screwed up.  I'll make a new one.

**Comment by DanGrayson** [comment]
Good, now the diff contains only 6 files.  The branch, from now on, will be https://github.com/Macaulay2/flint2/tree/Macaulay2-branches

**Comment by DanGrayson** [comment]
Why are such substantive changes to flint's cmake files required?

In fact, they don't seem to be required, since some involve comments.

**Comment by mahrud** [comment]
They are necessary for our CMake build to work with it and link with the same modules.

**Comment by DanGrayson** [comment]
> They are necessary for our CMake build to work with it and link with the same modules.

Hmm?  Some of the changes involve comments.  For example, changing "# Try to find the GMP library" to "# Try to find the GNU Multiple Precision Arithmetic Library (GMP)".

**Comment by mahrud** [comment]
I'm keeping it in sync with our version.

**Comment by DanGrayson** [comment]
> I'm keeping it in sync with our version.

What commit did you base your changes on?

**Comment by mahrud** [comment]
I don't understand what you're asking. I changed back the FindModules. Is this good now? I'm not interested in looking into their difference and hashing out what has changed and what hasn't

**Pull request merged**
