### PR TITLE
Macaulay2 patch

### PR DESCRIPTION
**Pull request by mahrud**
Manually reset this branch to point to 635f1f657c80e865ecdfd96db913fb8774371d8d.

### CODE REVIEW

**Comment by DanGrayson** [comment]
This pull request has conflicts, and it changes 5000 files.

**Comment by mahrud** [comment]
Dan, instead of just closing, could you do the following:
```
git checkout Macaulay2-patch
git reset 635f1f657c80e865ecdfd96db913fb8774371d8d
git push --force
```

**Comment by DanGrayson** [comment]
It's moot, anyway, the thing is set up now.

**Comment by mahrud** [comment]
I want to keep the history linear. Otherwise next time when it's time to patch the next version it'll be difficult to figure out what changes are needed. It's just three commands. If you don't have time to do it, give me push access and I'll do it.

**Comment by DanGrayson** [comment]
That's the beauty of "git merge" -- you don't have to patch the next version again.  And there's no need to keep the history linear.

**Comment by DanGrayson** [comment]
In the future, let's not use pull requests for pulling changes from upstream -- pull requests should be limited to incremental changes that are small enough to be easily reviewed.

**Comment by mahrud** [comment]
When you work with a patched repository, it's better to rebase the patch when a new version comes. There are no incremental changes here. Just rebase the patch commit on top of v2.7.1 so the patch is at the end.

**Comment by DanGrayson** [comment]
Well, that's one possible viewpoint on things, I suppose.  Not one I share though.  In particular, I'd prefer to keep the dates in the history intact.

**Pull request closed without merging**
