### PR TITLE
Macaulay2 patch

### PR DESCRIPTION
**Pull request by mahrud**
Manually reset this branch to point to 4922377644e418fe879f78e5f969bc6427264f69.

### CODE REVIEW

**Comment by DanGrayson** [comment]
No, we should preserve the "trunk" branch for matching exactly with the upstream trunk branch, but you have commits of your own on this branch.

**Comment by mahrud** [comment]
Just one patch at the top. Feel free to change the target branch, but that's how having a fork works.

**Comment by DanGrayson** [comment]
Okay, I made a new branch based on the upstream trunk to serve as the target, but there are numerous conflicts.

**Comment by mahrud** [comment]
I don't understand what you're doing. Do you want the branch from which CMake builds flint2 to be named `mahrud-patches`? That seems silly. These are Macaulay2's patches.

The conflicts clearly indicates that you're doing something wrong. I'm simply adding a single (1) commit on top of `v2.8.3` release tag.

**Comment by mahrud** [comment]
In particular, I don't understand why you treat flint2 differently than, say, the forks of [frobby](https://github.com/Macaulay2/frobby/tree/Macaulay2-patches) or [fflas_ffpack](https://github.com/Macaulay2/fflas-ffpack/tree/Macaulay2-patches), which have a branch named `Macaulay2-patches` with our patches at the end, occasionally rebased on top of the upstream branch.

**Comment by DanGrayson** [comment]
I also don't know why we don't have a branch here named Macaulay2-patches, so I made one based on v2.8.3.  Will that work for you?

**Comment by mahrud** [comment]
Yes. We had this branch for a long time (e.g. [here](https://github.com/Macaulay2/flint2/pull/3)), but at the last [update](https://github.com/Macaulay2/flint2/pull/9) you disagreed with my plan of rebasing the single commit patch on top of an upstream release tag and for some reason removed the branch.

**Pull request merged**
