### PR TITLE
Macaulay2 patch for 2.7.1

### PR DESCRIPTION
**Pull request by mahrud**

### CODE REVIEW

**Comment by DanGrayson** [comment]
This pull request has conflicts.   I'll take care of it at this end ...

**Comment by DanGrayson** [comment]
done in commit 6ddfd31ffd077c3ded0928c20416d815df729a6b

**Comment by mahrud** [comment]
That's why I was asking you to do it, since someone would need to do this manually anyway and I don't have push access. Also, why are there multiple `Macaulay2-patch` branches now? Why not just have one?

**Comment by mahrud** [comment]
Also, I don't know how you produced that commit, but the history of it is nonlinear now. Why don't you use rebase? There's one patch commit that needs to come on top of the v2.7.1 tag. There's no need for a merge!

**Comment by DanGrayson** [comment]
The previous patch branch got screwed up for an unknown reason, so I'm leaving a trail of breadcrumbs.

**Comment by mahrud** [comment]
The commits are still there. No reason to leave a train of screwed up branches behind.

**Comment by DanGrayson** [comment]
That's true -- could probably delete those old branches.

**Pull request closed without merging**
